server:
  port: 8082
  servlet:
    context-path: /api/v1
springdoc:
  swagger-ui:
    path: /documentation
spring:
  application:
    name: API-User-Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${CLIENT-ID:904875487615152139}
            client-secret: XRn5edHCrv3QIKyplU2T8nDqbhmJOWcw
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
              - email
            redirect-uri: "http://localhost:8080/"
            client-name: :root
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: ${USER_INFO:https://discordapp.com/api/users/@me}
            usernameAttribute: id
access:
  accounts:
    ${ACCOUNT_ONE:464890935067672576},
    ${ACCOUNT_SECOND:692324662826237972}

