server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: API-User-Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
springdoc:
  swagger-ui:
    path: /documentation
