server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  application:
    name: API-User-Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  security:
    user:
      name: admin
      password: 21232F297A57A5A743894A0E4A801FC3
springdoc:
  swagger-ui:
    path: /documentation
